#!/bin/sh
if [ -n "$2" ]; then
	file=$2
else
	file="/var/zero.txt"
fi
start=`date +%s`
if [ -n "$1" ]; then
	dd if=/dev/zero of=$file bs=1 count=0 seek=$1
else
	dd if=/dev/zero of=$file
fi
finish=`date +%s`
length=`echo "($finish - $start) + (23*60*60)" | bc`

chmod 0777 $file
chown www-data $file
chgrp www-data $file

echo "[zerofill]: executed $file in `date +%Hh%Mm%Ss --date=@$length` to `ls $file -lh | cut -d' ' -f 5`"

if [[ ! -n "$1" ]] ; then
	halt
fi
