#!/bin/sh
file="/var/zero.txt"
start=`date +%s`
if [[ -n "$1" ]] ; then
	time dd if=/dev/zero of=$file bs=1 count=0 seek=$1
else
	time dd if=/dev/zero of=$file
fi
finish=`date +%s`
length=`echo "($finish - $start) + (23*60*60)" | bc`

chmod 0777 $file
chown www-data $file
chgrp www-data $file

echo "[zerofill]: executed in `date +%Hh%Mm%Ss --date=@$length`"

if [[ ! -n "$1" ]] ; then
	halt
fi
