#!/bin/sh
if [ -n "$2" ]; then
	file=$2
else
	file="/var/zero.txt"
fi
if [ -n "$3" ]; then
	dev=$3
else
	dev="/dev/zero"
fi
start=`date +%s`
if [ -n "$1" ]; then
	#dd if=$dev of=$file bs=1 count=1 seek=$1
	dd if=$dev of=$file count=$1 bs=1 seek=1
else
	dd if=$dev of=$file
fi
finish=`date +%s`
length=`echo "($finish - $start) + (23*60*60)" | bc`

chmod 0777 $file
chown www-data $file
chgrp www-data $file

echo "[zerofill]: executed $file in `date +%Hh%Mm%Ss --date=@$length` to `ls $file -lh | cut -d' ' -f 5`"

if [ ! -n "$1" ]; then
	halt
fi
